
	<aside class="artists">
		<h2>About the artists</h2>
		<p>Each Featured Artist has an opportunity to speak at the conference to share his or her vision, perspective, and techniques with conference attendees. To get more information about the artists click on one of their photos, or visit our <a href="artists.php">artists</a> page.</p>
		<?php include('includes/artists-photogrid.inc'); ?>
		<a href="artists.php"><button type="button" class="btn btn-danger">About the artists</button></a>		
	</aside>
