	<aside class="last-year">
		<h2>Last year</h2>					
		<p>Did you miss last year's conference? Check out some photos from the event.</p>
		
		<div class="modalphotos photogrid clearfix">
			<img src="images/slides/artist_on_table_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />	
			<img src="images/slides/at_the_museum_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />	
			<img src="images/slides/charcoal_artist_painting_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />	
			<img src="images/slides/framing_workshop_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />	
			<img src="images/slides/glassmaking_workshop_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />
			<img src="images/slides/glassworking_workshop_tn.jpg" data-toggle="modal" data-target="#modal" class="img-thumbnail" />	
		</div>					
	</aside>