	<aside class="schedule">
		<h2>Schedule</h2>
		<p>There's a lot happening at our many workshop and talks. Make sure you check out the <a href="schedule.php">full schedule</a> for more information

		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		  <div class="panel">
			<div class="panel-heading" role="tab" id="headingOne">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">			
					 <span class="glyphicon glyphicon-calendar"></span> Monday
				</a>			  
			</div>
			<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
			  <div class="panel-body">
				<p>The first day of CAC events and exhibits is kicked off under the theme of Art in Full Color. From a demonstration in graffiti art on a wall of the Rousseau Room, to the exhibit of colorful glazed modern glassware in the Dover Hall, Art in Full Color will get CAC started in full swing!</p>
				<p><a href="schedule.php#monday"><button class="btn btn-danger">Monday's schedule</button></a></p>
			  </div>
			</div>
		  </div>
		  <div class="panel panel">
			<div class="panel-heading" role="tab" id="headingTwo">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
				  <span class="glyphicon glyphicon-calendar"></span> Tuesday
				</a>
			</div>
			<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
			  <div class="panel-body">
				<p>Water in Art is the theme for the second day, as art students from around the world gather at the Fountain of Intrigue in the gardens of Hotel Contempo to create ice sculptures, and art lecturers discuss the use of water as an art material, and water as an art subject.</p>
				<p><a href="schedule.php#tuesday"><button class="btn btn-danger">Tuesday's schedule</button></a></p>
			  </div>
			</div>
		  </div>
		  <div class="panel panel">
			<div class="panel-heading" role="tab" id="headingThree">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
				  <span class="glyphicon glyphicon-calendar"></span> Wednesday
				</a>
			</div>
			<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
			  <div class="panel-body">
				<p>From the diversity of pieces in Barot Bellingham's The Un-Collection to the tiny paintings and sculptures of Xhou Ta, Wednesday's sessions will contain unique art like you've never seen before. The funny and whip-smart Rita Ellsworth, MBA, will finish out the day giving practical advice on thriving as a professional artist in The Business of Art</p>
				<p><a href="schedule.php#wednesday"><button class="btn btn-danger">Wednesday's schedule</button></a></p>				
			  </div>
			</div>
		  </div>

		  <div class="panel panel">
			<div class="panel-heading" role="tab" id="headingFour">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
				  <span class="glyphicon glyphicon-calendar"></span> Thursday
				</a>
			</div>
			<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
			  <div class="panel-body">
				<p>Providing definition to abstract art, salvaging recyclables and collectibles for creating mixed media art, and a hands-on lesson in color theory are the hot topics for Thursday's lineup. Join Riley Rudolph Rewington, Constance Olivia Smith, and Hassum Harrod, some of the most talented up-and-coming artists of their generation.</p>
				<p><a href="schedule.php#thursday"><button class="btn btn-danger">Thursday's schedule</button></a></p>				
			  </div>
			</div>
		  </div>
		  <div class="panel panel">
			<div class="panel-heading" role="tab" id="headingFive">
				<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
				  <span class="glyphicon glyphicon-calendar"></span> Friday
				</a>
			</div>
			<div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
			  <div class="panel-body">
				<p>Meet the artists and view the art at your own pace on Friday. The day is reserved as an open day to explore on your own, the many art offerings of the conference.
				<p><a href="schedule.php#friday"><button class="btn btn-danger">Friday's schedule</button></a></p>				
			  </div>
			</div>
		  </div>		  
	</aside>