<div id="monday" class="tab-pane fade in active">
	<h2>Art in Full Color</h3>
	<p>The first day of CAC events and exhibits is kicked off under the theme of Art in Full Color From a demonstration in graffiti art on a wall of the Rousseau Room, to the exhibit of colorful glazed modern glassware in the Dover Hall, Art in Full Color will get CAC started in full swing!</p>
	
	<ul class="media-list">
		<li class="media">
			<div class="pull-left">
				<a href="artists.php#LaVonne_LaRue"><img class="media-object img-rounded" src="images/artists/LaVonne_LaRue_tn.jpg" data-toggle="tooltip" data-placement="auto bottom" title="LaVonne LaRue" /></a>
			</div>							
			<div class="media-body">
				<h4>9:30-10:30am</h4>									
				<h3 class="media-heading">Art in Unexpected Places</h3>
				<h4>Elizabeth Hall</h4>									
				<p>Watch LaVonne L. LaRue, a Chicago graffiti artist share her love and skill of mural art on Monday's schedule, as she starts the painting of a 20-foot high wall in the Rousseau Room of Hotel Contempo, which will be finished at the end of the conference. Make sure to show up a bit early, as this session will be standing-room only.</p>
			</div>
		</li>
		<li class="media">
			<div class="pull-left">
				<a href="artists.php#Lorenzo_Garcia"><img class="media-object img-rounded" src="images/artists/Lorenzo_Garcia_tn.jpg" data-toggle="tooltip" data-placement="auto bottom" title="Lorenzo Garcia" /></a>
			</div>							
			<div class="media-body">
				<h4>11:00am-1pm</h4>									
				<h3 class="media-heading">Art in Full Bloom</h3>
				<h4>Victoria Hall</h4>									
				<p>Drawing and painting flowers may seem like a first-year art student's assignment, but Lorenzo Garcia brings depth, shadows, light, and color to new heights with his unique technique of painting on canvas with ceramic glaze. This session is sure to be a hit with mixed media buffs.</p>
			</div>
		</li>							
	</ul>
	<h4>2:30-4:00pm</h4>
	<h3 class="media-heading">Still Life</h3>
	<h4>Dennison Hall</h4>
	<p>Grab your pencils, charcoal, acrylics, watercolors, or whatever painting tools suit your fancy, and participate in the capturing of various still life settings that are staged all around Dennison Hall. You won't believe the wealth and depth of choices.</p>
</div>