<div id="tuesday" class="tab-pane fade in">
	<h2>Water in Art</h3>
	<p>The first day of CAC events and exhibits is kicked off under the theme of Art in Full Color From a demonstration in graffiti art on a wall of the Rousseau Room, to the exhibit of colorful glazed modern glassware in the Dover Hall, Art in Full Color will get CAC started in full swing!</p>
	
	<ul class="media-list">
		<li class="media">
			<div class="pull-left">
				<a href="artists.php#Jennifer_Jerome"><img class="media-object img-rounded" src="images/artists/Jennifer_Jerome_tn.jpg" data-toggle="tooltip" data-placement="auto bottom" title="Jennifer Jerome" /></a>
			</div>							
			<div class="media-body">
				<h4>9:30-10:30am</h4>									
				<h3 class="media-heading">Water in Art Kickoff Session</h3>
				<h4>Elizabeth Hall</h4>									
				<p>Jennifer Jerome, a native of New Orleans, whose work has centered around abstract images that depict flooding and rebuilding, will talk about how the floods inspired her artistically, and how, despite the sadness of devastation and lives lost, her work also depicts the hope and togetherness of a community that has persevered.</p>
			</div>
		</li>
		<li class="media">
			<div class="pull-left">
				<a href="artists.php#Gerard_Donahue"><img class="media-object img-rounded" src="images/artists/Gerard_Donahue_tn.jpg" data-toggle="tooltip" data-placement="auto bottom" title="Gerard Donahue" /></a>
			</div>							
			<div class="media-body">
				<h4>10:30am-1pm</h4>
				<h3 class="media-heading">Ice Sculptures</h3>
				<h4>Fountain of Intrigue</h4>
				<p>Get on your mittens and earmuffs, and join your fellow artists at the Fountain of Intrigue, in the Hotel Contempo gardens, where the ambient temperature has been turned down to allow the sculpting of ice into the most mysterious and beautiful of shapes. Gerard Kent Donahue will share his secrets for chiseling ice into a shape that your imagination has envisioned. There is an extra fee of $25 for the rental of the tools needed to sculpt ice, if you plan to participate. And we hope you do!</p>
			</div>
		</li>							
		<li class="media">
			<div class="pull-left">
				<a href="artists.php#Hillary_Goldwynn"><img class="media-object img-rounded" src="images/artists/Hillary_Goldwynn_tn.jpg" data-toggle="tooltip" data-placement="auto bottom" title="Hillary Goldwynn" /></a>
			</div>							
			<div class="media-body">
				<h4>2:30-4:00pm</h4>
				<h3 class="media-heading">Deep Sea Wonders</h3>
				<h4>Dennison Hall</h4>
				<p>Hilary Goldywynn Post has been inspiring deep sea divers to paint what they experience under water, since she began diving at the early age of 14. Not only does she explain texture, color, and tools, but she also explains methods for capturing your under sea explorations in your mind for future expulsion onto canvas. And, even if snorkeling is as far under water as you're willing to go, Hilary's techniques will work just as well for you.</p>
			</div>
		</li>									
	</ul>
</div>