<div class="photogrid clearfix">
	<a href="artists.php#Barot_Bellingham"><img src="images/artists/Barot_Bellingham_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Barot Bellingham"  /></a>
	<a href="artists.php#Constance_Smith"><img src="images/artists/Constance_Smith_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Constance Smith"  /></a>
	<a href="artists.php#Gerard_Donahue"><img src="images/artists/Gerard_Donahue_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Barot Bellingham"  /></a>
	<a href="artists.php#Hassum_Harrod"><img src="images/artists/Hassum_Harrod_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Gerard Donahue"  /></a>
	<a href="artists.php#Hillary_Goldwynn"><img src="images/artists/Hillary_Goldwynn_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Hillary Goldwynn"  /></a>
	<a href="artists.php#Jennifer_Jerome"><img src="images/artists/Jennifer_Jerome_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Jennifer Jerome"  /></a>
	<a href="artists.php#Jonathan_Ferrar"><img src="images/artists/Jonathan_Ferrar_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Jonathan Ferrar"  /></a>
	<a href="artists.php#LaVonne_LaRue"><img src="images/artists/LaVonne_LaRue_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="LaVonne LaRue"  /></a>
	<a href="artists.php#Lorenzo_Garcia"><img src="images/artists/Lorenzo_Garcia_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Lorenzo Garcia"  /></a>
	<a href="artists.php#Richard_Tweed"><img src="images/artists/Richard_Tweed_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Richard Tweed"  /></a>
	<a href="artists.php#Riley_Rewington"><img src="images/artists/Riley_Rewington_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Riley Rewington"  /></a>
	<a href="artists.php#Xhou_Ta"><img src="images/artists/Xhou_Ta_tn.jpg" class="img-circle" data-toggle="tooltip" data-placement="auto top" title="Xhou Ta"  /></a>
</div>