			<section id="gallery">	
				<div id="myCarousel" class="carousel slide hidden-xs" data-ride="carousel">		
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
					<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					<li data-target="#myCarousel" data-slide-to="1"></li>
					<li data-target="#myCarousel" data-slide-to="2"></li>
					<li data-target="#myCarousel" data-slide-to="3"></li>
					<li data-target="#myCarousel" data-slide-to="4"></li>        
				  </ol>
				  <div class="carousel-inner" role="listbox">
					<div class="item active">
					  <img class="first-slide" src="images/carousel/acrilycs_workshop.jpg" alt="First slide">
					  <div class="container">
						<div class="carousel-caption">
						<!--
						  <h1>Example headline.</h1>
						  <p>Some text can go here for descring the images</p>
						  <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
						-->
						</div>
					  </div>
					</div>
					<div class="item">
					  <img class="second-slide" src="images/carousel/painting_workshop.jpg" alt="Second slide">
					  <div class="container">
						<div class="carousel-caption">
			
						</div>
					  </div>
					</div>
					<div class="item">
					  <img class="third-slide" src="images/carousel/pottery_finished.jpg" alt="Third slide">
					  <div class="container">
			
					  </div>
					</div>
					<div class="item">
					  <img class="fourth-slide" src="images/carousel/seattle_skyline.jpg" alt="Fourth slide">
					  <div class="container">
			
					  </div>
					</div>        
					<div class="item">
					  <img class="fith-slide" src="images/carousel/woodworking_workshop.jpg" alt="Fith slide">
					  <div class="container">
			
					  </div>
					</div>                
				  </div>
				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				  </a>
				</div>
			</section>