	</section>
	
	<footer class="row text-center">
		<div class="col-sm-12">
			<!--<ul class="breadcrumb">
				<li><a href="#">Home</a></li>
				<li><a href="#">Item 2</a></li>
				<li><a href="#">Item 3</a></li>
			</ul>-->
			<p>Copyright Roax Accademy &copy; <?php echo date('Y'); ?></p>					
		</div>		
	</footer>




    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
	<script src="js/min/myscript-min.js"></script>    