<div class="container">
	<div class="row">
		<header>
			<a href="index.php"><img src="images/misc/ralogo_monogram.png"></a>
		</header>

		<nav id="nav" class="navbar navbar-default navbar-static" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="index.php">Home</a></li>			
					<li><a href="venue.php">Venue/Travel</a></li>
					<li><a href="schedule.php">Schedule</a></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" data-target=".dropdown" href="#">Artists <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="artists.php">All Artists</a></li>						
							<li class="divider"></li>							
							<li><a tabindex="-1" href="artists.php#Barot_Bellingham">Barot Bellingham</a></li>
							<li><a tabindex="-1" href="artists.php#Gerard_Donahue">Gerard Donahue</a></li>
							<li><a tabindex="-1" href="artists.php#Jonathan_Ferrar">Jonathan Ferrar</a></li>
							<li><a tabindex="-1" href="artists.php#Lorenzo_Garcia">Lorenzo Garcia</a></li>
							<li><a tabindex="-1" href="artists.php#Hillary_Goldwynn">Hillary Goldwynn</a></li>
							<li><a tabindex="-1" href="artists.php#Hassum_Harrod">Hassum Harrod</a></li>
							<li><a tabindex="-1" href="artists.php#Jennifer_Jerome">Jennifer Jerome</a></li>
							<li><a tabindex="-1" href="artists.php#LaVonne_LaRue">LaVonne LaRue</a></li>
							<li><a tabindex="-1" href="artists.php#Riley_Rewington">Riley Rewington</a></li>
							<li><a tabindex="-1" href="artists.php#Constance_Smith">Constance Smith</a></li>
							<li><a tabindex="-1" href="artists.php#Xhou_Ta">Xhou Ta</a></li>
							<li><a tabindex="-1" href="artists.php#Richard_Tweed">Richard Tweed</a></li>
						</ul>
					</li>
					<li><a href="register.php">Register</a></li>
				</ul>
			</div>
		</nav>				
		

	</div>

		<section id="modal" class="modal fade">
			<div class="modal-body">
				<img id="modalimage" src="" class="img-responsive" />	
			</div>
		</section>		
		
	<section class="main">